### ISSUE TITLE
[Bug] CADMIN testcases failed in the UI.

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/certification-tool#120]
### Describe the bug

For the below mentioned CADMIN testcases are failed with the error : `Test Step Error: Error occurred during execution of test case TC-CADMIN-1.5. no close frame received or sent` 

- TC-CADMIN-1.5
- TC-CADMIN-1.9
- TC-CADMIN-1.21
- TC-CADMIN-1.22

### Log files

[tc-cadmin-1-5dut.txt](https://github.com/project-chip/matter-test-scripts/files/13659029/tc-cadmin-1-5dut.txt)
[cadmin-1-5.log](https://github.com/project-chip/matter-test-scripts/files/13659035/cadmin-1-5.log)

### Screenshots

![image](https://github.com/project-chip/certification-tool/assets/104007654/5b8d166b-3eb9-43a9-814b-da3bd72db536)

### Environment

Browser: Chrome

**Comment by ccruzagralopes** [comment]
Same error as:
- https://github.com/project-chip/certification-tool/issues/39
- https://github.com/project-chip/certification-tool/issues/117

**Comment by Saravana-kr22** [comment]
This issue is still not resolved in latest TH `Version: 2.10-beta2.1+spring2024
Sha: 549e33f`

**Comment by Saravana-kr22** [comment]
This issue is still not resolved in latest TH Version: `Version: 2.10-beta3+spring2024
Sha: 1fd1429`

**Comment by yf-fan-org** [comment]
@ccruzagralopes ple help, This issue is still not resolved in latest TH

**Comment by KishokG** [comment]
Tested in latest TH and issue is not resolved.

Same error in: TC-CADMIN-1.16

TH version: v2.11-beta2+fall2024
Sha: bbeda31

**Comment by fabiowmm** [comment]
Fixed.

**Comment by KishokG** [comment]
Still this issue is not fixed. Tested in Version: v2.12-beta3+spring2025, Sha: 729573d

**Affected test cases:** 

- TC-CADMIN-1.16
- TC-CADMIN-1.21
- TC-CADMIN-1.22

Logs for reference:  [CADMIN_Failure_logs.zip](https://github.com/user-attachments/files/18881652/CADMIN_Failure_logs.zip)

**Screenshot:** 

![Image](https://github.com/user-attachments/assets/9cff2bc9-8797-485e-b5b3-f8f674cb7168)


@rquidute I don't have access to re-opening the issue, Could you please re-open this issue?

**Comment by rquidute** [comment]
Reopening the issue as requested

**Comment by mlsg** [comment]
Any updates on this issue? still appears in v2.20.2+spring2024 
https://github.com/project-chip/certification-tool/issues/533

**Comment by oxesoft** [comment]
Closed due to inactivity.
